apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  selector:
    matchLabels:
      app: adservice
  template:
    metadata:
      labels:
        app: adservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "9555"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://appd-otel-collector.opentelemetry-controller.svc.cluster.local:4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=adservice,service.version=1.0.0
        image: docker.io/jholmes/adservice:1.0.0
        imagePullPolicy: IfNotPresent
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:9555
        #   initialDelaySeconds: 60
        #   periodSeconds: 15
        name: server
        ports:
        - containerPort: 9555
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:9555
        #   initialDelaySeconds: 60
        #   periodSeconds: 15
        resources:
          limits:
            cpu: 600m
            memory: 600Mi
          requests:
            cpu: 400m
            memory: 360Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: adservice
spec:
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555
  selector:
    app: adservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - env:
        - name: REDIS_ADDR
          value: redis-cart:6379
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://appd-otel-collector.opentelemetry-controller.svc.cluster.local:4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=cartservice,service.version=1.0.0,telemetry.sdk.language=dotnet
        image: docker.io/jholmes/cartservice:1.0.0
        imagePullPolicy: IfNotPresent
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:7070
        #     - -rpc-timeout=5s
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        name: server
        ports:
        - containerPort: 7070
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:7070
        #     - -rpc-timeout=5s
        #   initialDelaySeconds: 15
        resources:
          limits:
            cpu: 300m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 64Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
spec:
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
  selector:
    app: cartservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
spec:
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:50051
        - name: PAYMENT_SERVICE_ADDR
          value: paymentservice:50051
        - name: EMAIL_SERVICE_ADDR
          value: emailservice:5000
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice:7000
        - name: CART_SERVICE_ADDR
          value: cartservice:7070
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://appd-otel-collector.opentelemetry-controller.svc.cluster.local:4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=checkoutservice,service.version=1.0.0
        image: docker.io/jholmes/checkoutservice:1.0.0
        imagePullPolicy: IfNotPresent
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:5050
        name: server
        ports:
        - containerPort: 5050
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:5050
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
spec:
  ports:
  - name: grpc
    port: 5050
    targetPort: 5050
  selector:
    app: checkoutservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "7000"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://appd-otel-collector.opentelemetry-controller.svc.cluster.local:4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=currencyservice,service.version=1.0.0
        image: docker.io/jholmes/currencyservice:1.0.0
        imagePullPolicy: IfNotPresent
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:7000
        name: server
        ports:
        - containerPort: 7000
          name: grpc
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:7000
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
spec:
  ports:
  - name: grpc
    port: 7000
    targetPort: 7000
  selector:
    app: currencyservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://appd-otel-collector.opentelemetry-controller.svc.cluster.local:4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=emailservice,service.version=1.0.0
        image: docker.io/jholmes/emailservice:1.0.0
        imagePullPolicy: IfNotPresent
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:8080
        #   periodSeconds: 5
        name: server
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:8080
        #   periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
spec:
  ports:
  - name: grpc
    port: 5000
    targetPort: 8080
  selector:
    app: emailservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: frontend
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: CURRENCY_SERVICE_ADDR
          value: currencyservice:7000
        - name: CART_SERVICE_ADDR
          value: cartservice:7070
        - name: RECOMMENDATION_SERVICE_ADDR
          value: recommendationservice:8080
        - name: SHIPPING_SERVICE_ADDR
          value: shippingservice:50051
        - name: CHECKOUT_SERVICE_ADDR
          value: checkoutservice:5050
        - name: AD_SERVICE_ADDR
          value: adservice:9555
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://appd-otel-collector.opentelemetry-controller.svc.cluster.local:4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=frontend,service.version=1.0.0
        - name: ENV_PLATFORM
          value: azure
        image: docker.io/jholmes/frontend:1.0.0
        imagePullPolicy: IfNotPresent
        # livenessProbe:
        #   httpGet:
        #     httpHeaders:
        #     - name: Cookie
        #       value: shop_session-id=x-liveness-probe
        #     path: /_healthz
        #     port: 8080
        #   initialDelaySeconds: 10
        name: server
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   httpGet:
        #     httpHeaders:
        #     - name: Cookie
        #       value: shop_session-id=x-readiness-probe
        #     path: /_healthz
        #     port: 8080
        #   initialDelaySeconds: 10
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "50051"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://appd-otel-collector.opentelemetry-controller.svc.cluster.local:4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=paymentservice,service.version=1.0.0
        image: docker.io/jholmes/paymentservice:1.0.0
        imagePullPolicy: IfNotPresent
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:50051
        name: server
        ports:
        - containerPort: 50051
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:50051
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: paymentservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
spec:
  selector:
    matchLabels:
      app: productcatalogservice
  template:
    metadata:
      labels:
        app: productcatalogservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "3550"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://appd-otel-collector.opentelemetry-controller.svc.cluster.local:4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=productcatalogservice,service.version=1.0.0
        image: docker.io/jholmes/productcatalogservice:1.0.0
        imagePullPolicy: IfNotPresent
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:3550
        name: server
        ports:
        - containerPort: 3550
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:3550
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
spec:
  ports:
  - name: grpc
    port: 3550
    targetPort: 3550
  selector:
    app: productcatalogservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
spec:
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: productcatalogservice:3550
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://appd-otel-collector.opentelemetry-controller.svc.cluster.local:4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=recommendationservice,service.version=1.0.0
        image: docker.io/jholmes/recommendationservice:1.0.0
        imagePullPolicy: IfNotPresent
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:8080
        #   periodSeconds: 5
        name: server
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:8080
        #   periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 450Mi
          requests:
            cpu: 100m
            memory: 220Mi
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
spec:
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  selector:
    app: recommendationservice
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
spec:
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - image: redis:alpine
        # livenessProbe:
        #   periodSeconds: 5
        #   tcpSocket:
        #     port: 6379
        name: redis
        ports:
        - containerPort: 6379
        # readinessProbe:
        #   periodSeconds: 5
        #   tcpSocket:
        #     port: 6379
        resources:
          limits:
            cpu: 125m
            memory: 256Mi
          requests:
            cpu: 70m
            memory: 200Mi
        volumeMounts:
        - mountPath: /data
          name: redis-data
      volumes:
      - emptyDir: {}
        name: redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis-cart
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - env:
        - name: PORT
          value: "50051"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: http://appd-otel-collector.opentelemetry-controller.svc.cluster.local:4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=shippingservice,service.version=1.0.0
        image: docker.io/jholmes/shippingservice:1.0.0
        imagePullPolicy: IfNotPresent
        # livenessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:50051
        name: server
        ports:
        - containerPort: 50051
        # readinessProbe:
        #   exec:
        #     command:
        #     - /bin/grpc_health_probe
        #     - -addr=:50051
        #   periodSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
      serviceAccountName: default
---
apiVersion: v1
kind: Service
metadata:
  name: shippingservice
spec:
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  selector:
    app: shippingservice
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
      labels:
        app: loadgenerator
    spec:
      containers:
      - env:
        - name: FRONTEND_ADDR
          value: frontend:80
        - name: USERS
          value: "25"
        image: docker.io/jholmes/loadgenerator:1.0.0
        name: main
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
      initContainers:
      - command:
        - /bin/sh
        - -exc
        - |
          echo "Init container pinging frontend: ${FRONTEND_ADDR}..."
          STATUSCODE=$(wget --server-response http://${FRONTEND_ADDR} 2>&1 | awk '/^  HTTP/{print $2}')
          if test $STATUSCODE -ne 200; then
              echo "Error: Could not reach frontend - Status code: ${STATUSCODE}"
              exit 1
          fi
        env:
        - name: FRONTEND_ADDR
          value: frontend:80
        image: busybox:latest
        name: frontend-check
      restartPolicy: Always
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
