appdynamics-cloud-k8s-monitoring:
  clustermonConfig:
    clusterName: terraform-dev-charleslin
    events:
      enabled: true
      severityToExclude: []
      reasonToExclude: []
      severeGroupByReason: []
  install:
    logCollector: true
 
  logCollectorConfig:
    container:
      conditions:
        - condition:
            operator: equals
            key: kubernetes.pod.name
            value: adservice
          multiLinePattern:
          multiLineNegate:
          multiLineMatch:
          messageParser:
            log4J:
              enabled: true
              pattern: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg trace_id=%X{trace_id} span_id=%X{span_id} trace_flags=%X{trace_flags} %n"
            logback:
              enabled:
              pattern:
            timestamp:
              enabled:
              format:
            json:
              enabled:
              timestampField:
              timestampPattern:
              flattenSep:
              fieldsToIgnore:
              fieldsToIgnoreRegex:
              maxNumOfFields:
              maxDepth:
            grok:
              enabled:
              patterns:
              timestampField:
              timestampPattern:
            infra:
              enabled:
      clusterName: terraform-dev-charleslin
      dropFields: []
      batchSize:
      loggingLevel:
      loggingSelectors: []
      monitoring:
        enabled:
        loggingPeriod:
    filebeatYaml: ""
    
appdynamics-otel-collector:
  # see collectors-values-sensitive.yaml for the following setting
  # clientId: <clientId>
  # clientSecret: <clientSecret>
  # tenantId: <tenantId>
  # endpoint: https://lab1.observe.appdynamics.com

